import type { Metadata } from "next";
import "./globals.css";
import { Lato } from "next/font/google";
import NarBar from "./components/NavBar/NavBar";
import Footer from "./components/Footer";

const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700", "900"],
  variable: "--body-font",
});

export const metadata: Metadata = {
  title: "Shina's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${lato.className} scroll-smooth`}>
        <NarBar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
